config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  root 'home#index'
  get 'home/about'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index , :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    redirect_to new_user_session_path if !user_signed_in? 
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    # puts @friend.to_json
    redirect_to  friends_path , notice: "Not Authorized to edit/remove this friend " if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # puts 'hello world =============================== '
  end

  def about 
    @mario_path = "My Name is Mario Monir"  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
  <div class="field col mb-3">
    <%= form.label :first_name, class:"form-label", required:"true" %>
    <%= form.text_field :first_name, class:"form-control", required:true %>
  </div>

  <div class="field col mb-3">
    <%= form.label :last_name, class:"form-label"%>
    <%= form.text_field :last_name, class:"form-control", required:true %>
  </div>
  </div>

  <div class="field col mb-3">
    <%= form.label :email, class:"form-label" %>
    <%= form.text_field :email ,class:"form-control", required:true %>
  </div>

  <div class="field col mb-3">
    <%= form.label :phone, class:"form-label" %>
    <%= form.text_field :phone, class:"form-control", required:true %>
  </div>


  <div class="field col mb-3">
    <%= form.label :twitter, class:"form-label"%>
    <%= form.text_field :twitter, class:"form-control", required:true%>
  </div>

  
  <div class="field col mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", type: :hidden ,value:current_user.id  , required:true%>
  </div>


  <div class="actions text-center mt-5">
    <%= form.submit class:"btn btn-outline-success" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<div class="d-flex justify-content-between align-items-center my-4">
  <h1>Editing Friend</h1>
  <div>
    <%= link_to 'Show', @friend , class:"btn btn-outline-primary btn-sm" %> 
    <%= link_to 'Back', friends_path  , class:"btn btn-outline-primary btn-sm"%>
  <%= link_to 'Remove' , @friend , method: :delete , data: {confirm:"Are you sure you want delete this friend "}  ,class:"btn btn-outline-danger btn-sm m-1"%>

  </div>
</div>


<%= render 'form', friend: @friend %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-between  align-items-center">
  <h1>Friends</h1>
  <%= link_to 'New Friend', new_friend_path , class: "btn btn-outline-primary"  if user_signed_in?%>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <%# <th>Last name</th> %>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <%# <th>User Id</th> %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each_with_index do |friend , index| %>
      <% if friend.user == current_user %>
        <tr class='clickable-row' data-href='url://link-for-first-row/'>
          <td><%= index+1  %></td>
          
          <td><%= link_to (friend.first_name+" "+friend.last_name), friend , class: "btn btn-outline-dark border-0 fst-italic"  %></td>
          <%# <td><%= friend.first_name %1></td> %> 
          <%# <td><%= friend.last_name %1></td> %>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          <%# <td><%= friend.user_id %1></td> %>
          <%# <td><%= link_to 'Show', friend, class: "btn btn-outline-primary btn-sm"  %1></td> %>
          <td><%= link_to 'Edit', edit_friend_path(friend) ,class: "btn btn-outline-primary btn-sm" ,  title:"Edit" if  current_user == friend.user %></td>
          <td><%= link_to 'Delete' , friend, method: :delete, data: { confirm: 'Are you sure you want to remove your friend ?' } , class: "btn btn-outline-danger btn-sm" , title:"Remove" if current_user == friend.user  %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/friends/new.html.erb
<div class="d-flex justify-content-between align-items-center my-4">
  <h1>New Friend</h1>
  <%= link_to 'Back', friends_path  , class:"btn btn-outline-primary"%>
</div>
<%= render 'form', friend: @friend %>

app/views/friends/show.html.erb
<div class="p-5 mb-5 bg-light border rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold"> 
      <%= @friend.first_name %> 
      <%= @friend.last_name %> 
    </h1>
    
    <p class="col-md-8 fs-4">
      <strong>Email:</strong>
      <%= @friend.email %>
    </p>

    <p class="col-md-8 fs-4">
      <strong>Phone:</strong>
      <%= @friend.phone %>
    </p>
    
    <p class="col-md-8 fs-4">
      <strong>Twitter:</strong>
      <%= @friend.twitter %>
    </p>

    <%= link_to 'Back', friends_path, class: "btn btn-outline-primary btn-sm m-1" %>
    <% if current_user == @friend.user %>
      <%= link_to 'Edit', edit_friend_path(@friend),class:"btn btn-outline-primary btn-sm m-1"%>
      <%= link_to 'Remove' , @friend , method: :delete , data: {confirm:"Are you sure you want delete this friend "}  ,class:"btn btn-outline-danger btn-sm m-1"%>

    <% end %>
  </div>
</div>

app/views/home/about.html.erb
<h1>About us page <%= @mario_path %></h1>

app/views/home/index.html.erb
<h1> Hello <%= current_user.email  if user_signed_in? %></h1>

app/views/layouts/_alert.html.erb
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong>Alert ! : </strong> <%= alert %>.
</div>

app/views/layouts/_footer.html.erb
<%# <footer class="footer"> %>
<%#   <div class="container" > %>
<%#     <p class="float-end"><a href="#">Back to top</a></p> %>
<%#     <p>&copy; 2021 MarioMonir, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p> %>
<%#   </div> %>
<%# </footer> %>

app/views/layouts/_header.html.erb
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
  <%# <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none"> %>
  <%#   <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg> %>
  <%#   <span class="fs-4"> %>
  <%#     <%= link_to 'Friend' , root_path %1> %>
  <%#   </span> %>
  <%# </a> %>

  <%= link_to 'Friends' , root_path , class:"d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none h3"%> 

  <ul class="nav nav-pills">
    <li class="nav-item">
      <u><%= link_to '/home' , root_path , class:"nav-link link-dark"%></u>
    </li>

  <% if user_signed_in? %>
    <li class="nav-item">
      <u><%= link_to '/friends' , friends_path , class:"nav-link link-dark"%></u>
    </li> 
  <%end%>

    <li class="nav-item">
      <u><%= link_to '/about' , home_about_path , class:"nav-link link-dark"%></u>
    </li>

    <% if user_signed_in? %>
      <li class="nav-item">
        <u><%= link_to '/Sign out', destroy_user_session_path, method: :delete,class:"nav-link link-dark"%></u>
      </li>
  
      <li class="nav-item">
        <u><%= link_to '/My Profile',edit_user_registration_path,class:"nav-link link-dark"%></u>
      </li>
    <% else %>
      <li class="nav-item">
        <u><%= link_to '/Sign up',new_user_registration_path,class:"nav-link link-dark"%></u>
      </li>

      <li class="nav-item">
        <u><%= link_to '/Sign in',user_session_path,class:"nav-link link-dark"%></u>
      </li>
  
    <% end %>



  </ul>
</header>

app/views/layouts/_notice.html.erb
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  <strong>Notice ! : </strong> <%= notice %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container px-5 pb-5">
      <%= render :partial => 'layouts/header'  %>
      <main class="flex-shrink-0">
        <%= render "layouts/notice" if notice %>
        <%# <%= render "layouts/alert" if alert %1> %>
        <%= yield %>
      </main>
    </div>
    <%= render :partial => 'layouts/footer'  %>
</body>
</html>